// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BookstoreNameController from "./bookstore_name_controller"
application.register("bookstore-name", BookstoreNameController)

import FilterDateController from "./filter_date_controller"
application.register("filter-date", FilterDateController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import PotatoController from "./potato_controller"
application.register("potato", PotatoController)
