// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ControllerController from "./controller_controller"
application.register("controller", ControllerController)

import FilterDateController from "./filter_date_controller"
application.register("filter-date", FilterDateController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import PayModalController from "./pay_modal_controller"
application.register("pay-modal", PayModalController)

import PotatoController from "./potato_controller"
application.register("potato", PotatoController)
